-- Drop tables if they exist to allow clean recreations
-- (Note: Foreign Key constraints will drop on CASCADE)
-- Run this script in your Oracle XE workspace

-- 1. USERS
CREATE TABLE USERS (
    USER_ID      VARCHAR2(50) PRIMARY KEY,
    FULL_NAME    VARCHAR2(100) NOT NULL,
    EMAIL        VARCHAR2(150) NOT NULL UNIQUE,
    PASSWORD     VARCHAR2(100) NOT NULL,
    COLLEGE_NAME VARCHAR2(150) NOT NULL,
    DEPARTMENT   VARCHAR2(80) NOT NULL,
    ROLE         VARCHAR2(50) NOT NULL
);

-- 2. PROJECTS
CREATE TABLE PROJECTS (
    PROJECT_ID              VARCHAR2(50) PRIMARY KEY,
    NAME                    VARCHAR2(100) NOT NULL,
    DOMAIN                  VARCHAR2(100),
    HEALTH                  NUMBER(3) DEFAULT 100,
    PHASE                   VARCHAR2(50),
    MENTOR_NAME             VARCHAR2(100),
    PROGRESS                NUMBER(3) DEFAULT 0,
    STATUS                  VARCHAR2(50) DEFAULT 'Healthy',
    DESCRIPTION             VARCHAR2(1000),
    COMMITS                 NUMBER(9) DEFAULT 0,
    PRS                     NUMBER(9) DEFAULT 0,
    ISSUES_CLOSED           NUMBER(9) DEFAULT 0,
    CONTRIBUTION_PERCENT    NUMBER(3) DEFAULT 0,
    REPO_URL                VARCHAR2(255),
    TEAM_NAME               VARCHAR2(100)
);

-- 3. TEAMS
CREATE TABLE TEAMS (
    TEAM_ID       VARCHAR2(50) PRIMARY KEY,
    NAME          VARCHAR2(100) NOT NULL,
    PROJECT_ID    VARCHAR2(50),
    PROJECT_NAME  VARCHAR2(100),
    MENTOR_NAME   VARCHAR2(100),
    HEALTH        NUMBER(3) DEFAULT 100,
    LEADER_NAME   VARCHAR2(100),
    MEMBERS_COUNT NUMBER(3) DEFAULT 0,
    STATUS        VARCHAR2(50) DEFAULT 'Good',
    RANK          NUMBER(5)
);

-- 4. TASKS
CREATE TABLE TASKS (
    TASK_ID           VARCHAR2(50) PRIMARY KEY,
    PROJECT_ID        VARCHAR2(50) NOT NULL,
    NAME              VARCHAR2(150) NOT NULL,
    DEADLINE          VARCHAR2(50),
    PRIORITY          VARCHAR2(20),
    STATUS            VARCHAR2(20) DEFAULT 'To Do',
    ASSIGNED_DATE     DATE,
    REPORT_SUBMITTED  NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_TASK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID) ON DELETE CASCADE
);

-- 5. MILESTONES
CREATE TABLE MILESTONES (
    MILESTONE_ID VARCHAR2(50) PRIMARY KEY,
    PROJECT_ID   VARCHAR2(50) NOT NULL,
    NAME         VARCHAR2(150) NOT NULL,
    DUE_DATE     VARCHAR2(50),
    PROGRESS     NUMBER(3) DEFAULT 0,
    STATUS       VARCHAR2(20) DEFAULT 'Pending',
    CONSTRAINT FK_MILESTONE_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID) ON DELETE CASCADE
);

-- 6. WEEKLY_REPORTS
CREATE TABLE WEEKLY_REPORTS (
    REPORT_ID         VARCHAR2(50) PRIMARY KEY,
    PROJECT_ID        VARCHAR2(50) NOT NULL,
    WEEK              VARCHAR2(50),
    REMARKS           VARCHAR2(1000),
    SUBMISSION_STATUS VARCHAR2(50) DEFAULT 'Submitted',
    SUBMITTED_DATE    DATE,
    FILE_NAME         VARCHAR2(150),
    FILE_SIZE         VARCHAR2(30),
    FILE_URL          VARCHAR2(255),
    CONSTRAINT FK_REPORT_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID) ON DELETE CASCADE
);
